
#KOS_CFLAGS+= -pedantic -ansi -Ibuilds/unix -Iinclude
KOS_CFLAGS+= -Ibuilds/unix -Iinclude

TARGET = libfreetype.a

OBJS =	\
	src/base/ftsystem.o \
	src/base/ftdebug.o \
	src/base/ftinit.o \
	src/base/ftbase.o \
	src/base/ftglyph.o \
	src/base/ftmm.o \
	src/base/ftbbox.o \
	src/autohint/autohint.o \
	src/cache/ftcache.o \
	src/cff/cff.o \
	src/cid/type1cid.o \
	src/pcf/pcf.o \
	src/psaux/psaux.o \
	src/pshinter/pshinter.o \
	src/psnames/psnames.o \
	src/raster/raster.o \
	src/sfnt/sfnt.o \
	src/smooth/smooth.o \
	src/truetype/truetype.o \
	src/type1/type1.o \
	src/winfonts/winfnt.o \


include $(KOS_BASE)/addons/Makefile.prefab
