
CC = arm-elf-gcc
AS = arm-elf-as
LD = 	arm-elf-ld
OBJCOPY = arm-elf-objcopy

DEPENDFILE	=	Makedepend
MAPFILE		=	primitives.map
TARGET_ELF	=	primitives.elf
TARGET_BIN	=	primitives.gxb
TARGET_FXE	=	primitives.fxe
LDSCRIPT	=	lnkscript
X_LDSCRIPT	= 	arm-gp32bin.x



.SFILES =	crt0x_gp32.s 

.CFILES	=	primitives.c

.OFILES	=	$(.SFILES:.s=.o) $(.CFILES:.c=.o)


OPTFLAGS =	-mtune=arm920 -march=armv4t -marm -mno-thumb-interwork \
		-msoft-float -ffast-math -nostdlib -fno-common \
		-ffreestanding -fno-builtin -fno-exceptions \
		-mstructure-size-boundary=8 -fomit-frame-pointer \
		-fstrict-aliasing -O6 \


CFLAGS	=	-I/opt/gp32/include/SDL -I../../include \
		$(OPTFLAGS) -DGFXST -DGP32 -DGP32_LIBC \
		-Wall -Wno-switch -DUSE_FIXED_POINT \

LDFLAGS	=	-Map $(MAPFILE) -nostartfiles --script $(X_LDSCRIPT) \
		-L/opt/gp32/arm-elf/lib -L/opt/gp32/lib/gcc/arm-elf/3.4.1
		
SYSTEMLIBS =	-lSDLx_gfx -lSDLx_image -lSDLx \
		-lpng_x -ljpeg_x -lz_x -lx_gp32 -lm -lgcc

DOLINK =	$(LD) $(LDFLAGS) $(.OFILES) $(SYSTEMLIBS) -o $(TARGET_ELF)


$(TARGET_FXE): $(TARGET_BIN)
	b2fxec $< $@

$(TARGET_BIN): $(TARGET_ELF)
	$(OBJCOPY) -O binary $< $@

$(TARGET_ELF): $(.OFILES) $(DEPENDFILE)
	$(DOLINK)


.PHONY: all clean depend

all:    clean depend $(TARGET_BIN)

tags:	$(DEPENDFILE)
	ctags -e *.c *.s *.h *.S

clean:
	-rm -f $(.OFILES) $(DEPENDFILE) $(MAPFILE) $(TARGET_ELF) $(TARGET_BIN) $(TARGET_FXE) TAGS

send: $(TARGET_FXE)
	gplink -c -x put $(TARGET_FXE) /GPMM

depend:
	$(CC) $(CFLAGS) -M $(.CFILES) > $(DEPENDFILE)

$(DEPENDFILE):
	$(CC) $(CFLAGS) -M $(.CFILES) > $(DEPENDFILE)

include $(DEPENDFILE)
