TARGET	=	framerate.exe


CC =		gcc
STRIP=		strip


SDL_CFLAGS =	`sdl-config --cflags` -DWIN32 -DFSL -DTARGET_WIN32 -DTARGET_win32 -DTARGET_windows
SDL_LDFLAGS =	`sdl-config --libs`


CFLAGS =	-Wall -Wno-switch -march=pentium -mcpu=pentium ${SDL_CFLAGS} \
		-ffast-math -fno-common -ffreestanding -fno-builtin -Isrc/ \
		-fno-exceptions -fstrict-aliasing -O6 -I/usr/local/include \
		-I../../include \

CFLAGS+=-DDLLINTERFACE=""


LDFLAGS =	-L../../lib -L/usr/lib -lSDL_gfx -lSDL_image ${SDL_LDFLAGS} \
		-lpng -lz -ljpeg \



.CFILES	=	framerate.c


all: $(TARGET)



OBJS =		$(.CFILES:.c=.o)


$(TARGET):	$(OBJS)
	$(CC) -L../../lib -L/usr/local/lib -o $(TARGET) -lmingw32 $(OBJS) -lSDL_gfx -lSDL_static -mwindows -mno-cygwin -luser32 -lgdi32 -lwinmm
	$(STRIP) $(TARGET)


run:		$(TARGET)
	./$(TARGET)


clean:
	rm -f $(OBJS) $(TARGET) stdout.txt stderr.txt
